package Splash;

import Login.TelaLogin;
import ConexaoDB.ConexaoBD;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gustavo Gonçalves
 * 18/06/2018
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreenMarkTest
     */
    public SplashScreen() {
        initComponents();
        //TESTE (Estudar classe Color depois)
        this.setBackground(new Color(0, 255, 0, 0)); //deixar o background invisivel

        new Thread() {
            @Override
            //@Override = sobreescrevendo um método já existente
            public void run() {
                for (int i = 0; i < 101; i++) //enquanto i for menor que 101, faz um incremento de 1 em 1
                {
                    try { //Circundando codigo com try catch para tratar possiveis erros
                        sleep(20); //tempo que vai carregar a progressbar (milissegundos)
                        jProgressBar1.setValue(i); //define o valor da progressbar com o "i"
                        if (jProgressBar1.getValue() <= 40) //se o valor de carregamento do progressbar for menor ou igual a 40 (40%)
                        {
                            lblSplash.setText("Carregando banco de dados..."); //Troca o nome do lblSplash

                            //TESTAR CONEXAO COM BANCO DE DADOS:
                            Connection con = ConexaoBD.conectar();
                            //
                        } else //se o valor de carregamento do progressbar for OUTRO diferente de menor ou igual a 40 (40%)
                        {
                            lblSplash.setText("Carregando sistema..."); //Troca o nome do lblSplash
                            //Sem testar nenhuma funcionalidade por enquanto
                        }

                    //Tratamento de erros:    
                    } catch (InterruptedException | SQLException ex) {
                        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    //
                    
                }
                dispose(); //Fechar a SplashScreen
                TelaLogin tn = new TelaLogin(); //Instanciando objeto tn da classe TelaLogin
                tn.setLocationRelativeTo(null); //Centralizar form.
                tn.setVisible(true); //Fazer o form ficar visível
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSplashIMG = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblSplash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblSplashIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo_Mark.png"))); // NOI18N

        jProgressBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jProgressBar1.setStringPainted(true);

        lblSplash.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSplash.setText("lblSplash");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSplashIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSplashIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblSplash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(386, 288));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblSplash;
    private javax.swing.JLabel lblSplashIMG;
    // End of variables declaration//GEN-END:variables
}
