package Login;

import Principal.TelaPrincipal;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo Gonçalves
 * 07/06/2018
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaNova
     */
    public TelaLogin() {
        this.initComponents();
        //this.setSize(576, 359);
        this.setTitle("OLD SCHOOL v 1.0 [BETA]");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        lblUser = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        btnEntrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnEntrar.setBackground(new java.awt.Color(253, 192, 71));
        btnEntrar.setText("Entrar");
        btnEntrar.setActionCommand("Teste");
        btnEntrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(230, 240, 120, 50);
        btnEntrar.getAccessibleContext().setAccessibleName("btnTeste");

        txtLogin.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin);
        txtLogin.setBounds(190, 140, 200, 30);

        txtSenha.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(190, 190, 200, 30);

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUser.setText("E-mail:");
        getContentPane().add(lblUser);
        lblUser.setBounds(120, 140, 70, 30);

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(120, 190, 60, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bg.jpg"))); // NOI18N
        lblBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBackground.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblBackgroundKeyPressed(evt);
            }
        });
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 560, 320);
        lblBackground.getAccessibleContext().setAccessibleName("jLabelPainel");

        btnEntrar1.setBackground(new java.awt.Color(253, 192, 71));
        btnEntrar1.setText("Entrar");
        btnEntrar1.setActionCommand("Teste");
        btnEntrar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar1);
        btnEntrar1.setBounds(230, 250, 110, 50);

        setSize(new java.awt.Dimension(576, 359));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        try {
            //BOTAO LOGIN
            LoginPrincipal login = new LoginPrincipal(); //Instanciando o objeto login
            //
            if(login.permissaoLogar(txtLogin.getText(), txtSenha.getText())) 
            //Se o usuario e senha digitar no campo de dados retornar valor 
            //verdadeiro do metodo permissaoLogar(), ele entra no sistema. 
            {
                JOptionPane.showMessageDialog(null, "Acesso permitido!");
                TelaPrincipal telaPrincipal = new TelaPrincipal(); //Instanciando o objeto telaPrincipal da classe TelaPrincipal
                this.dispose(); //Fechar o form de login
                telaPrincipal.setLocationRelativeTo(null); //Centralizar form principal
                telaPrincipal.setVisible(true); //Exibir form principal
            }
            else
            {
                this.txtSenha.setText(""); //Limpar caixa de texto senha
                this.txtSenha.requestFocus(); //Focar na caixa de testo senha
                JOptionPane.showMessageDialog(null, "Nome ou senha incorreto.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao logar: " + ex);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        //Evento KeyPressed no textfield senha (quando vc clica alguma tecla)
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) //Se vc aperte a tecla enter: 
        {
            this.btnEntrar.doClick(); //executa a ação do botao Entrar
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void lblBackgroundKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblBackgroundKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblBackgroundKeyPressed

    private void btnEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnEntrar1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
