package Controle;

import DAO.CRUD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.SQLException;

/**
 *
 * @author Gustavo Gonçalves
 * 14/06/2018
 */
public class PainelEstoque extends javax.swing.JFrame 
{
    
    public PainelEstoque() throws SQLException {
        this.initComponents(); //Inicializar os componentes do form
        DefaultTableModel modelo = (DefaultTableModel) this.jtblFuncaoSelect.getModel(); //Define o modelo do jTable
        this.jtblFuncaoSelect.setRowSorter(new TableRowSorter(modelo)); //Ordenando a tabela
        this.setTitle("OLD SCHOOL v 1.0 [BETA]"); //Define o titulo do form
        this.setResizable(false);
    }

    public void lerJTable() throws SQLException 
    {
        //METODO PARA LER O JTABLE
        DefaultTableModel modelo = (DefaultTableModel) this.jtblFuncaoSelect.getModel(); //Define o modelo do jTable
        modelo.setNumRows(0); //Define o número de linhas padrao

        CRUD p2 = new CRUD(); //Instancia o objeto "p2" da classe de funções mysql

        for (Estoque p : p2.lerSelect()) //função forEach
        {
            //Pega os dados e joga no jTable
            modelo.addRow(new Object[]{
                //id, nomeBebida, lote, qtd, validade, tipo, recebimento, preco
                p.getId(),
                p.getNomeBebida(),
                p.getLote(),
                p.getQtd(),
                p.getValidade(),
                p.getTipo(),
                p.getRecebimento(),
                p.getPreco(),
                p.getPrecoTotal()
            });
            //
        }
    }
    
    public void lerJTablePorID(String atributo, int posicao) throws SQLException 
    {
        //METODO PARA LER O JTABLE POR UMA VARIAVEL DEFINIDA NO COMBOBOX
        DefaultTableModel modelo = (DefaultTableModel) this.jtblFuncaoSelect.getModel(); //Define o modelo do jTable
        modelo.setNumRows(0); //Define o número de linhas padrao

        CRUD p2 = new CRUD(); //Instancia o objeto "p2" da classe de funções mysql
        for (Estoque p : p2.lerSelectPorId(atributo, cbbMenuBuscaOpcao.getSelectedIndex())) //função forEach
        {            
            //Pega os dados e joga no jTable
            modelo.addRow(new Object[]{
                //id, nomeBebida, lote, qtd, validade, tipo, recebimento, preco
                p.getId(),
                p.getNomeBebida(),
                p.getLote(),
                p.getQtd(),
                p.getValidade(),
                p.getTipo(),
                p.getRecebimento(),
                p.getPreco()
            });
            //
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        txtNomeBebida = new javax.swing.JTextField();
        txtLote = new javax.swing.JTextField();
        txtValidade = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblLote = new javax.swing.JLabel();
        lblValidade = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        lblRecebimento = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        txtRecebimento = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        lblQtd = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        cbbMenuBuscaOpcao = new javax.swing.JComboBox<>();
        painelMenu = new javax.swing.JPanel();
        scrollPainel = new javax.swing.JScrollPane();
        jtblFuncaoSelect = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setText("Nome");

        lblLote.setText("Lote de Fabricação");

        lblValidade.setText("Validade");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        txtBusca.setToolTipText("");
        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblTipo.setText("Tipo");

        lblRecebimento.setText("Data de Recebimento");

        lblPreco.setText("Preço (R$)");

        lblQtd.setText("Quantidade");

        cbbMenuBuscaOpcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome do Produto", "Lote de Fabricação", "Quantidade", "Validade", "Tipo de Produto" }));
        cbbMenuBuscaOpcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMenuBuscaOpcaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecebimento)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                                .addComponent(txtRecebimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNome))
                                .addGap(18, 18, 18)
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLote)
                                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPreco)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQtd)
                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValidade)
                            .addComponent(txtValidade, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                    .addComponent(txtPreco)
                    .addComponent(cbbMenuBuscaOpcao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblLote)
                    .addComponent(lblValidade)
                    .addComponent(lblQtd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(btnAtualizar)
                            .addComponent(btnExcluir)
                            .addComponent(btnCadastrar))
                        .addContainerGap())
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTipo)
                                    .addComponent(lblRecebimento)
                                    .addComponent(lblPreco))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbbMenuBuscaOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        lblValidade.getAccessibleContext().setAccessibleName("txtValidade");
        btnCadastrar.getAccessibleContext().setAccessibleDescription("COMANDO INSERT");

        jtblFuncaoSelect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Lote", "Quantidade", "Validade", "Tipo", "Recebimento", "Preço (R$)", "Total (R$)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblFuncaoSelect.getTableHeader().setReorderingAllowed(false);
        jtblFuncaoSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblFuncaoSelectMouseClicked(evt);
            }
        });
        jtblFuncaoSelect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtblFuncaoSelectKeyReleased(evt);
            }
        });
        scrollPainel.setViewportView(jtblFuncaoSelect);
        if (jtblFuncaoSelect.getColumnModel().getColumnCount() > 0) {
            jtblFuncaoSelect.getColumnModel().getColumn(0).setResizable(false);
            jtblFuncaoSelect.getColumnModel().getColumn(0).setPreferredWidth(25);
            jtblFuncaoSelect.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPainel)
                .addContainerGap())
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(724, 451));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            //BOTAO CADASTRAR
            
            Estoque p = new Estoque(); //Instancia o objeto "p" da classe de gets e sets
            CRUD p2 = new CRUD(); //Instancia o objeto "p2" da classe de funções mysql
            
            //id, nomeBebida, lote, qtd, validade, tipo, recebimento, preco
            
            //Joga os dados das jTextField pros metodos set
            p.setNomeBebida(txtNomeBebida.getText());
            p.setLote(txtLote.getText());
            p.setQtd(Integer.parseInt(txtQtd.getText()));
            p.setValidade(txtValidade.getText());
            p.setTipo(txtTipo.getText());
            p.setRecebimento(txtRecebimento.getText());
            p.setPreco(Double.parseDouble(txtPreco.getText()));
            //
            p2.salvarInsert(p); //Chama o metodo da classe de funções para inserir os dados no banco de dados 
            
            //Limpa as caixas de texto
            txtNomeBebida.setText("");
            txtLote.setText("");
            txtQtd.setText("");
            txtValidade.setText("");
            txtTipo.setText("");
            txtRecebimento.setText("");
            txtPreco.setText("");
            //
            this.lerJTable(); //Exibe os dados no jTable
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir os dados: " + ex);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //BOTAO EXCLUIR
        //Confirmação se deseja realmente excluir
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja excluir o item selecionado (ID: "+(int) jtblFuncaoSelect.getValueAt(jtblFuncaoSelect.getSelectedRow(), 0)+")?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION)
        {
        //
            if (this.jtblFuncaoSelect.getSelectedRow() != -1) //Se o indice da linha clicada for diferente de -1:
            {
                Estoque p = new Estoque();
                CRUD p2 = new CRUD();

                p.setId((int) jtblFuncaoSelect.getValueAt(jtblFuncaoSelect.getSelectedRow(), 0));

                try {
                    p2.deletarDelete(p);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro: " + ex);
                }

                txtNomeBebida.setText("");
                txtLote.setText("");
                txtQtd.setText("");
                txtValidade.setText("");
                txtTipo.setText("");
                txtRecebimento.setText("");
                txtPreco.setText("");

                try {
                    this.lerJTable();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro: " + ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum item selecionado.");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jtblFuncaoSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblFuncaoSelectMouseClicked
        //METODO MOUSECLICKED (QUANDO VC CLICA NOS DADOS EXIBIDOS NO JTABLE)
        if (this.jtblFuncaoSelect.getSelectedRow() != -1) //Se o indice da linha clicada for diferente de -1:
        {
            //id, nomeBebida, lote, qtd, validade, tipo, recebimento, preco
            
            //Joga os dados da linha que vc clicou para as jTextFields 
            this.txtNomeBebida.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 1).toString());
            this.txtLote.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 2).toString());
            this.txtQtd.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 3).toString());
            this.txtValidade.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 4).toString());
            this.txtTipo.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 5).toString());
            this.txtRecebimento.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 6).toString());
            this.txtPreco.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 7).toString());
            //
        }
    }//GEN-LAST:event_jtblFuncaoSelectMouseClicked

    private void jtblFuncaoSelectKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblFuncaoSelectKeyReleased
        //Reescrevendo codigos do jMouseClicked        
        //METODO KEYRELEASED (QUANDO VC DESCE AS LINHAS PELA SETA, NÃO NECESSARIAMENTE PRECISANDO CLICAR EM CADA LINHA DO JTABLE)
        if (this.jtblFuncaoSelect.getSelectedRow() != -1) //Se o indice da linha clicada for diferente de -1:
        {
            //id, nomeBebida, lote, qtd, validade, tipo, recebimento, preco
            
            //Joga os dados da linha que vc clicou para as jTextFields 
            this.txtNomeBebida.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 1).toString());
            this.txtLote.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 2).toString());
            this.txtQtd.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 3).toString());
            this.txtValidade.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 4).toString());
            this.txtTipo.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 5).toString());
            this.txtRecebimento.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 6).toString());
            this.txtPreco.setText(this.jtblFuncaoSelect.getValueAt(this.jtblFuncaoSelect.getSelectedRow(), 7).toString());
            //
        }
    }//GEN-LAST:event_jtblFuncaoSelectKeyReleased

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        //BOTAO ATUALIZAR
        if (this.jtblFuncaoSelect.getSelectedRow() != -1) //Se o indice da coluna clicada for diferente de -1:
        {
            try {
                Estoque p = new Estoque(); //Instanciando objeto "p" da classe de gets e sets dos dados
                CRUD p2 = new CRUD(); //Instanciando objeto "p2" da classe de funções mysql (crud)
                
                //id, nomeBebida, lote, qtd, validade, tipo, recebimento, preco
                
                //Joga os dados das jTextField pros metodos set
                p.setId((int) jtblFuncaoSelect.getValueAt(jtblFuncaoSelect.getSelectedRow(), 0)); //Puxa o ID da linha selecionada (indice 0)
                p.setNomeBebida(txtNomeBebida.getText()); 
                p.setLote(txtLote.getText());
                p.setQtd(Integer.parseInt(txtQtd.getText()));
                p.setValidade(txtValidade.getText());
                p.setTipo(txtTipo.getText());
                p.setRecebimento(txtRecebimento.getText());
                p.setPreco(Double.parseDouble(txtPreco.getText()));
                //
                p2.atualizarUpdate(p); //Chama o metodo da classe de funções para atualizar os dados no banco de dados 
                
                //Limpa as caixas de texto
                txtNomeBebida.setText("");
                txtLote.setText("");
                txtQtd.setText("");
                txtValidade.setText("");
                txtTipo.setText("");
                txtRecebimento.setText("");
                txtPreco.setText("");
                //
                this.lerJTable(); //Exibe os dados no jTable
                
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Erro ao atualizar os dados: " + ex);
            }
            
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //BOTAO BUSCAR
        try {
            if (txtBusca.getText().equals("") || txtBusca.getText().equals("*")) //Se o que tiver digitado no campo de texto "Busca" for igual a "" (vazio) ou "*"
            {
                this.lerJTable(); //Exibe os dados no jTable
            } 
            else 
            {
                this.lerJTablePorID(txtBusca.getText(), cbbMenuBuscaOpcao.getSelectedIndex()); //Exibe os dados  no jTable pesquisados por uma variável que você escolhe pelo combobox
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao exibir os dados: " + ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void cbbMenuBuscaOpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMenuBuscaOpcaoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbbMenuBuscaOpcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PainelEstoque().setVisible(true);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro: " + ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    public javax.swing.JComboBox<String> cbbMenuBuscaOpcao;
    public javax.swing.JTable jtblFuncaoSelect;
    private javax.swing.JLabel lblLote;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblRecebimento;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValidade;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JScrollPane scrollPainel;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNomeBebida;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtRecebimento;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtValidade;
    // End of variables declaration//GEN-END:variables
}